const express = require('express')

const destinoRoutes = require('../routes/destinoRoutes')
const planoRoutes  = require('../routes/planoRoutes')
const  propietariosRoutes = require('../routes/propietariosRoutes')
const altasRoutes = require('../routes/altasRoutes')
const userRoutes = require('../routes/userRoutes')
const auditLogsRoutes = require('../routes/auditLogsRoutes')
const searchAltasRoutes = require('../routes/searchAltasRoutes')
const metricsRoutes = require('../routes/metricsRoutes')
const auditoriaPlanosRoutes = require('../../destino/routes/auditoriaPlanosRoutes')    
const planoArchivoRoutes = require('../../destino/routes/planoArchivoRoutes')
const router = express.Router()

router.use('/user', userRoutes)
router.use('/destino', destinoRoutes)
router.use('/planos', planoRoutes)
router.use('/propietarios', propietariosRoutes)
router.use('/altas', altasRoutes)
// router.use('/audit', auditLogsRoutes)    
router.use('/search', searchAltasRoutes)
router.use('/metrics', metricsRoutes)
router.use('/auditoria', auditoriaPlanosRoutes)
router.use('/planoArchivo', planoArchivoRoutes)
module.exports = router